--- 
install: 
  - "pip install ."
language: python
notifications: 
  email: 
    on_failure: change
    on_success: never
    recipients: 
      - dlt@crest.iu.edu
  slack: "crest-networks:nctOxrMsZdnYU8jGrkpSjpvf"
python: 
  - "2.7"
script: "python test/test_utils.py"
virtualenv: 
  system_site_packages: true

