language: python 
python:
  - "2.7"
virtualenv:
  system_site_packages: true
install: 
  - "pip install ."
script: "python test/test_utils.py"
notifications: 
  email: 
    on_failure: change
    on_success: never
    recipients: 
      - dlt@crest.iu.edu
  slack: "crest-networks:nctOxrMsZdnYU8jGrkpSjpvf"
