#!/bin/bash
#
# supervisord   This scripts turns blipp on
#
# description:  blipp is a part of the Periscope measurement framework
#               which also includes UNIS and the MS. 
#
# processname:  blippd

# source function library
. /etc/rc.d/init.d/functions

BLIPPD_CONF_FILE="/etc/periscope/blipp_dlt.json"
lockfile=/var/lock/subsys/blippd

RETVAL=0

start() {
        [ -f $BLIPPD_CONF_FILE ] || exit 6
	echo -n $"Starting blippd: "
	daemon blippd -c $BLIPPD_CONF_FILE
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch $lockfile
        return $RETVAL
}

stop() {
	echo -n $"Stopping blippd: "
	killproc blippd
	echo
	[ $RETVAL -eq 0 ] && rm -f $lockfile
        return $RETVAL
}

restart() {
	stop
        sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop) 
	stop
	;;
  restart|force-reload|reload)
	restart
	;;
  condrestart)
	[ -f $lockfile ] && restart
	;;
  status)
	status blippd
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
	exit 1
esac

exit $RETVAL
